// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: image_streaming.proto
#ifndef GRPC_image_5fstreaming_2eproto__INCLUDED
#define GRPC_image_5fstreaming_2eproto__INCLUDED

#include "image_streaming.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace imagestreaming {

// Interface exported by server
class ImageStreaming final {
 public:
  static constexpr char const* service_full_name() {
    return "imagestreaming.ImageStreaming";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::imagestreaming::ImgRequest, ::imagestreaming::ImgResponse>> VideoStart(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::imagestreaming::ImgRequest, ::imagestreaming::ImgResponse>>(VideoStartRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imagestreaming::ImgRequest, ::imagestreaming::ImgResponse>> AsyncVideoStart(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imagestreaming::ImgRequest, ::imagestreaming::ImgResponse>>(AsyncVideoStartRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imagestreaming::ImgRequest, ::imagestreaming::ImgResponse>> PrepareAsyncVideoStart(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imagestreaming::ImgRequest, ::imagestreaming::ImgResponse>>(PrepareAsyncVideoStartRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void VideoStart(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::imagestreaming::ImgRequest,::imagestreaming::ImgResponse>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::imagestreaming::ImgRequest, ::imagestreaming::ImgResponse>* VideoStartRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::imagestreaming::ImgRequest, ::imagestreaming::ImgResponse>* AsyncVideoStartRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::imagestreaming::ImgRequest, ::imagestreaming::ImgResponse>* PrepareAsyncVideoStartRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::imagestreaming::ImgRequest, ::imagestreaming::ImgResponse>> VideoStart(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::imagestreaming::ImgRequest, ::imagestreaming::ImgResponse>>(VideoStartRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::imagestreaming::ImgRequest, ::imagestreaming::ImgResponse>> AsyncVideoStart(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::imagestreaming::ImgRequest, ::imagestreaming::ImgResponse>>(AsyncVideoStartRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::imagestreaming::ImgRequest, ::imagestreaming::ImgResponse>> PrepareAsyncVideoStart(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::imagestreaming::ImgRequest, ::imagestreaming::ImgResponse>>(PrepareAsyncVideoStartRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void VideoStart(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::imagestreaming::ImgRequest,::imagestreaming::ImgResponse>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::imagestreaming::ImgRequest, ::imagestreaming::ImgResponse>* VideoStartRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::imagestreaming::ImgRequest, ::imagestreaming::ImgResponse>* AsyncVideoStartRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::imagestreaming::ImgRequest, ::imagestreaming::ImgResponse>* PrepareAsyncVideoStartRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_VideoStart_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status VideoStart(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::imagestreaming::ImgResponse, ::imagestreaming::ImgRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_VideoStart : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_VideoStart() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_VideoStart() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VideoStart(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imagestreaming::ImgResponse, ::imagestreaming::ImgRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVideoStart(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::imagestreaming::ImgResponse, ::imagestreaming::ImgRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_VideoStart<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_VideoStart : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_VideoStart() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::imagestreaming::ImgRequest, ::imagestreaming::ImgResponse>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->VideoStart(context); }));
    }
    ~WithCallbackMethod_VideoStart() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VideoStart(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imagestreaming::ImgResponse, ::imagestreaming::ImgRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::imagestreaming::ImgRequest, ::imagestreaming::ImgResponse>* VideoStart(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_VideoStart<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_VideoStart : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_VideoStart() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_VideoStart() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VideoStart(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imagestreaming::ImgResponse, ::imagestreaming::ImgRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_VideoStart : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_VideoStart() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_VideoStart() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VideoStart(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imagestreaming::ImgResponse, ::imagestreaming::ImgRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVideoStart(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_VideoStart : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_VideoStart() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->VideoStart(context); }));
    }
    ~WithRawCallbackMethod_VideoStart() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VideoStart(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imagestreaming::ImgResponse, ::imagestreaming::ImgRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* VideoStart(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace imagestreaming


#endif  // GRPC_image_5fstreaming_2eproto__INCLUDED
