# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import image_streaming_pb2 as image__streaming__pb2


class ImageStreamingStub(object):
    """Interface exported by server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VideoStart = channel.stream_stream(
                '/imagestreaming.ImageStreaming/VideoStart',
                request_serializer=image__streaming__pb2.ImgRequest.SerializeToString,
                response_deserializer=image__streaming__pb2.ImgResponse.FromString,
                )


class ImageStreamingServicer(object):
    """Interface exported by server
    """

    def VideoStart(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageStreamingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VideoStart': grpc.stream_stream_rpc_method_handler(
                    servicer.VideoStart,
                    request_deserializer=image__streaming__pb2.ImgRequest.FromString,
                    response_serializer=image__streaming__pb2.ImgResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imagestreaming.ImageStreaming', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageStreaming(object):
    """Interface exported by server
    """

    @staticmethod
    def VideoStart(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/imagestreaming.ImageStreaming/VideoStart',
            image__streaming__pb2.ImgRequest.SerializeToString,
            image__streaming__pb2.ImgResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
